### ISSUE TITLE
Support for vanilla extract files

### ISSUE THREAD

**Issue by daniheras** [miguelsolorio/vscode-symbols#100]
Vanilla extract is becoming an increasingly well-known library of CSS Modules for writing type-safe locally scoped css classes, variables, etc...

Its files end up with .css.ts and the icon is a cupcake. vscode-icons support it.
https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_vanilla_extract.svg

**Comment by miguelsolorio** [comment]
<img width="196" alt="CleanShot 2023-06-13 at 08 55 37@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/bd1740e1-7cfc-478b-afaa-396eb9f8fa34">
