### ISSUE TITLE
Greater variety of icons for files and folders

### ISSUE THREAD

**Issue by nicolascodes18** [miguelsolorio/vscode-symbols#102]
Hello, I thought of the idea of bringing a greater variety of icons like we have in the "Material Icon Theme" package but using this more minimalist side of symbols.
Some examples would be icons for
- Layout
- Context
- Hook
- Middlware
- Database
- Templates
- Utils
- Controller
- Repositories
- Functions

Among others widely used by the community.
Thank you for this amazing package, I'm really enjoying it and recommending it to everyone.

**Comment by oresttokovenko** [comment]
To add to this, I would love a `.gif` icon

**Comment by miguelsolorio** [comment]
Added several folder icons, hopefully this will satisfy the list. If you have any other specific requests let me know:

<img width="219" alt="CleanShot 2023-08-04 at 15 50 20@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/85951194-80e2-4367-a612-6f5619f6700e">
