### ISSUE TITLE
Add support for `turbo.json` icon

### ISSUE THREAD

**Issue by taverasmisael** [miguelsolorio/vscode-symbols#105]
This icon set is pure fire.

Do you think you could add an icon for `turbo.json`? It is used to configure [Turbo repo](https://turbo.build/repo) projects.

Thanks for your work!

**Comment by andrefelipeschulle** [comment]
I created the icon, it's in PR #106, ;)

**Comment by andrefelipeschulle** [comment]
closed #106

**Comment by miguelsolorio** [comment]
<img width="205" alt="CleanShot 2023-08-04 at 11 12 14@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/b038ce7f-b407-4d69-9bf8-f0ad644759a6">
