### ISSUE TITLE
Add support for `.dev.vars` icon

### ISSUE THREAD

**Issue by shyakadavis** [miguelsolorio/vscode-symbols#110]
Hi.

May you please add support for the `.dev.vars` file. I've found myself using it more and more when I transitioned over to Cloudflare Workers, when storing secrets and whatnot.

Appreciate what you've done so far, Miguel. 🖤

**Comment by miguelsolorio** [comment]
<img width="189" alt="CleanShot 2023-08-04 at 13 55 32@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/982e9ee4-55c2-40c9-87d5-a92f66b8d9f0">
