### ISSUE TITLE
Add `CMakeLists.txt` icon

### ISSUE THREAD

**Issue by caoimhebyrne** [miguelsolorio/vscode-symbols#115]
I'm not a designer, but it would be nice if there was an icon for [CMake](https://cmake.org/)'s configuration file, `CMakeLists.txt`.

This is their official logo:
![image](https://github.com/miguelsolorio/vscode-symbols/assets/71222289/54582f61-9dfe-4c90-a4fd-d36964341ce1)

**Comment by caoimhebyrne** [comment]
This icon should also probably apply for `CMakeCache.txt`, and a folder variant for `CMakeFiles`?

**Comment by miguelsolorio** [comment]
<img width="175" alt="CleanShot 2023-09-25 at 14 13 57@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/5543cadd-a08c-4c39-a55e-d24f8a68d0b6">

**Comment by caoimhebyrne** [comment]
Looks awesome, thanks! @miguelsolorio
