### ISSUE TITLE
Add `.cshtml` and `.razor` files for .NET projects

### ISSUE THREAD

**Issue by evertonandrade** [miguelsolorio/vscode-symbols#116]

**Comment by miguelsolorio** [comment]
Fixed via https://github.com/miguelsolorio/vscode-symbols/pull/130

<img width="225" alt="CleanShot 2023-09-25 at 14 00 38@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/f1b1de85-78bb-4726-b54c-171b16e7284e">
