### ISSUE TITLE
ios folder icon

### ISSUE THREAD

**Issue by svipas** [miguelsolorio/vscode-symbols#117]
We now have `android` folder icon, it would be awesome to have one for `ios` folder. This a usual folder structure/naming for React Native projects.

**Comment by miguelsolorio** [comment]
<img width="133" alt="CleanShot 2023-09-25 at 14 23 37@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/5d8c8be9-9f19-41bc-bd42-e916ff99056d">
