### ISSUE TITLE
add support to EMS config file

### ISSUE THREAD

**Issue by andrefelipeschulle** [miguelsolorio/vscode-symbols#124]
Add support do postcss.config.mts and tailwind.config.mts

**Comment by andrefelipeschulle** [comment]
close to #125

**Comment by miguelsolorio** [comment]
Fixed via https://github.com/miguelsolorio/vscode-symbols/pull/125

<img width="214" alt="CleanShot 2023-09-25 at 13 54 16@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/1fd16276-a718-4fe2-ab45-f3f8ac2dfc0e">

<br>
<img width="193" alt="CleanShot 2023-09-25 at 13 54 05@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/5c77acc1-db3e-473f-a870-00a76cb223b0">
