### ISSUE TITLE
Feature Request: Add Icon for BunJS

### ISSUE THREAD

**Issue by tanishqmanuja** [miguelsolorio/vscode-symbols#131]
Live up to the hype xD

**Comment by miguelsolorio** [comment]
@tanishqmanuja can you provide a list of file extensions that would map to this? I am not familiar with Bun, thanks.

**Comment by tanishqmanuja** [comment]
Correct bun.lock, and [bunfig.toml](https://bun.sh/docs/runtime/bunfig)

**Comment by miguelsolorio** [comment]
Thanks for the quick response, will try and get this into the next release (hoping to publish today).

**Comment by miguelsolorio** [comment]
![CleanShot 2023-10-11 at 10 47 14@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/eef9fc02-2182-4951-a518-0d71746f6932)

**Comment by tanishqmanuja** [comment]
Thank You 💯
