### ISSUE TITLE
[Icon Request] Nest JS Icons and variants

### ISSUE THREAD

**Issue by FabianMontoya** [miguelsolorio/vscode-symbols#132]
**Describe the bug**
Nest js is based on angular and most of the icons could be reused

It would be fantastic to have it supported.

Thanks.

![Screenshot 2023-09-22 at 1 15 00 PM](https://github.com/miguelsolorio/vscode-fluent-icons/assets/37662924/dad2aa75-df29-4b88-a39e-38180e6b80fc)

**Expected behavior**
Can change the icon variant in NestJS projects as for ex, in Material Design Icons Pack:

![Screenshot 2023-09-22 at 1 15 25 PM](https://github.com/miguelsolorio/vscode-fluent-icons/assets/37662924/e94e2546-a40f-4f54-8227-0216f353b785)

**Screenshots**

Actual result:
![Screenshot 2023-09-22 at 1 15 00 PM](https://github.com/miguelsolorio/vscode-fluent-icons/assets/37662924/dad2aa75-df29-4b88-a39e-38180e6b80fc)

Expected behavior
![Screenshot 2023-09-22 at 1 15 25 PM](https://github.com/miguelsolorio/vscode-fluent-icons/assets/37662924/e94e2546-a40f-4f54-8227-0216f353b785)

**Additional context**
Material Design solve that with a flag in `settings.json`:

https://github.com/PKief/vscode-material-icon-theme/issues/503

**Comment by miguelsolorio** [comment]
Please see the files/folder association, you can configure this https://github.com/miguelsolorio/vscode-symbols#configuration

Ref https://github.com/miguelsolorio/vscode-symbols/issues/93

**Comment by FabianMontoya** [comment]
Is possible add more variants of the same icon?, for example for yellow and blue variant?
