### ISSUE TITLE
Add Icon for Drizzle config file and migration folder

### ISSUE THREAD

**Issue by tanishqmanuja** [miguelsolorio/vscode-symbols#133]
file: drizzle.config.ts
folder: drizzle and .drizzle

file icon can be this with a different color:
![drizzle](https://github.com/miguelsolorio/vscode-symbols/assets/40914272/6e6a55d7-c6a4-4c7f-9efc-660d3acd9c57)
(Taken directly from [drizzle](https://orm.drizzle.team/))

**Comment by miguelsolorio** [comment]
![CleanShot 2023-10-11 at 10 28 33@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/96612871-6ba2-4e94-98a5-e602dfc364d2)
