### ISSUE TITLE
OCaml Icon

### ISSUE THREAD

**Issue by smorimoto** [miguelsolorio/vscode-symbols#134]
You can find the original logo collection here: https://github.com/ocaml/ocaml-logo

**Comment by smorimoto** [comment]
Common OCaml file extensions: `.ml`, `.mli`

**Comment by miguelsolorio** [comment]
![CleanShot 2023-10-11 at 10 32 31@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/24498a69-12ed-419e-b352-94974376cd9f)

**Comment by smorimoto** [comment]
Fantastic!
