### ISSUE TITLE
Dune Icon

### ISSUE THREAD

**Issue by smorimoto** [miguelsolorio/vscode-symbols#137]
Related files: `dune`, `dune-project`, `dune-workspace`

https://dune.build

**Comment by smorimoto** [comment]
https://github.com/ocaml/dune/blob/main/doc/assets/imgs/dune_logo_459x116.png

**Comment by miguelsolorio** [comment]
![CleanShot 2023-10-11 at 10 44 43@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/43c59273-fc5d-4f7e-a8c1-0438d3f0a8b3)

**Comment by smorimoto** [comment]
Awesome!
