### ISSUE TITLE
Allow hiding explorer icons

### ISSUE THREAD

**Issue by net-tech** [miguelsolorio/vscode-symbols#138]
As of https://github.com/microsoft/vscode/pull/35856 icons can set `hidesExplorerArrows: true` to hide the arrows in the explorer next to each file and folder. Users cannot set this in their workspace settings. Maybe allow us to set something like `symbols.hideExporerArrows: true` to hide them, or when picking the file icon theme have an option called `Symbols (without explorer arrows)`?

**Comment by miguelsolorio** [comment]
Have you taken a look at the settings for the extension? We support `symbols.hidesExplorerArrows`:

![CleanShot 2023-10-15 at 09 43 55@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/bc0b1a34-1c32-411f-b97c-9a2529238e68)

**Comment by net-tech** [comment]
Weird, I didn't get it in intellisense when editing the json. Thanks and sorry for the useless open @miguelsolorio!
