### ISSUE TITLE
Add `keystatic` icon

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#139]
[keystatic](https://keystatic.com/)
file types: `keystatic.config.ts` and `keystatic.page.ts`

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-02 at 14 03 55@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/8ef9704a-ef6f-4e92-89fe-8e3092484e76)
