### ISSUE TITLE
Add `markdoc` icon

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#140]
[markdoc](https://markdoc.dev/)
file type: `.mdoc` and `markdoc.config.ts`

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 10 43 57@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/2fb9bf1f-4b42-4b62-b76a-e330e7dab3c1)
