### ISSUE TITLE
Add `sanity` icon

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#141]
[sanity](https://www.sanity.io/)
file types: `sanity.*.ts`

**Comment by miguelsolorio** [comment]
Wildcards aren't supported like that in file icons [per the api](https://code.visualstudio.com/api/extension-guides/file-icon-theme#file-association):

> `fileNames` associates file names to icons. The key in the set is the full file name, not including any path segments. Optionally, the file extension name can be prefixed by a single parent path segment (*). **Patterns or wildcards are not supported**. File name matching is case insensitive...

Is there a list of file name that are commonly used in sanity?

**Comment by miguelsolorio** [comment]
Added a few based on the usage in the sanity repo:

![CleanShot 2024-01-03 at 10 58 59@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/18a4c4e7-cfd8-45b7-b834-4901a0f65306)
