### ISSUE TITLE
add a status icon when a folder is open

### ISSUE THREAD

**Issue by warcayac** [miguelsolorio/vscode-symbols#142]
Like this:

![image](https://github.com/miguelsolorio/vscode-symbols/assets/7342885/c8cd4e6b-7287-4e1d-985a-0e3d4664edcf)

or using colors like this 

![image](https://github.com/miguelsolorio/vscode-symbols/assets/7342885/654906fa-5536-42c4-9bc6-5f7c223d8007)

**Comment by miguelsolorio** [comment]
Merging this with https://github.com/miguelsolorio/vscode-symbols/issues/49 which is asking for the same functionality
