### ISSUE TITLE
How to resize the icon

### ISSUE THREAD

**Issue by Lzzzs** [miguelsolorio/vscode-symbols#143]
How to resize the icon

**Comment by miguelsolorio** [comment]
@Lzzzs can you please add more information of what you are trying to do? I don't understand what you are asking

**Comment by Lzzzs** [comment]
okay. I want to adjust the size of icon. Is there any configuration that can be adjusted? I haven't seen it
![image](https://github.com/miguelsolorio/vscode-symbols/assets/74575471/80aea05b-434f-4266-81a6-719ec1a9905a)

**Comment by dreambit** [comment]
Is it possible?

**Comment by miguelsolorio** [comment]
No, these icons are static and can't be resized (it would require a new feature request). You can zoom in/out in the VS Code UI.
