### ISSUE TITLE
icon for panda config

### ISSUE THREAD

**Issue by calvo-jp** [miguelsolorio/vscode-symbols#144]
Custom icon for [panda](https://github.com/chakra-ui/panda) config (`panda.config.ts`)

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 04 02@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/594efe78-2608-4b3e-8a1b-24b0852bee5c)
