### ISSUE TITLE
Add icon for solidity

### ISSUE THREAD

**Issue by danitome24** [miguelsolorio/vscode-symbols#145]
[Solidity lang](https://soliditylang.org/)

files types: `*.sol`

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 19 02@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/9c68bc41-32b4-4782-9e2d-5da6f297c4a4)

**Comment by danitome24** [comment]
Thanks a lot @miguelsolorio and happy new year
