### ISSUE TITLE
Add icon for serverless framework

### ISSUE THREAD

**Issue by robertocerdasilva** [miguelsolorio/vscode-symbols#146]
[Serverless Framework](https://www.serverless.com/)
file: serverless.yml

Thanks :D

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 24 09@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/d5782795-e3d1-442c-b7e8-c16828d30619)
