### ISSUE TITLE
Add GatsbyJS icon

### ISSUE THREAD

**Issue by robertocerdasilva** [miguelsolorio/vscode-symbols#148]
[Gatsby](https://www.gatsbyjs.com/)
file: gatsby-config.js or gatsby-{ SOME }.js

Thanks :D

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 09 35@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/fa5afd63-b7c3-4c19-9ea7-3775144812bd)
