### ISSUE TITLE
Add `unocss` icon

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#154]
https://unocss.dev/
logo: https://unocss.dev/logo.svg
file types: `uno.config.{js,ts,mjs,mts}`

**Comment by miguelsolorio** [comment]
<img width="288" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/9cd637e6-92ed-407b-a98b-ea86fd964c28">
