### ISSUE TITLE
github folder icon

### ISSUE THREAD

**Issue by FabianMontoya** [miguelsolorio/vscode-symbols#158]
Please add github folder variant for the folder `.github` or only the variant.

The actual folder-gray is ok, but if it's possible to create and add, it could be great.

Thanks!!

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 50 19@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/03fde780-d5c8-4b84-896b-f4acc619f56d)
