### ISSUE TITLE
Supabase and firebase folder icon

### ISSUE THREAD

**Issue by FabianMontoya** [miguelsolorio/vscode-symbols#159]
Please add a Supabase and firebase folder icon for the folder `supabase` and `firebase`, it could be great.

I actually have this folder association, but if you can add the variant could be great.

```
"symbols.folders.associations": {
    "firebase": "folder-yellow",
    "supabase": "folder-green",
  }
```

**Comment by miguelsolorio** [comment]
![CleanShot 2024-01-03 at 11 55 20@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/e9fd5bc4-56c6-474d-9f2c-32a318e8da8d)

![CleanShot 2024-01-03 at 11 55 27@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/b9b80b49-2956-4a23-9dfb-34c29010d324)
