### ISSUE TITLE
Add angular service icon

### ISSUE THREAD

**Issue by pedroslp** [miguelsolorio/vscode-symbols#166]
Add angular service icon (*.service.js / *.service.ts), is the same as the angular icon one, but in yellow (could be amber/400)

**Comment by miguelsolorio** [comment]
![CleanShot 2024-03-12 at 11 25 04@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/b265fd41-0433-4010-9672-0dcf9390a3e4)
