### ISSUE TITLE
Add haskell

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#167]
file ext: `.hs`
https://www.haskell.org/
![Haskell logo](https://github.com/miguelsolorio/vscode-symbols/assets/44789941/a24e5f07-409a-4972-850c-1b3e01613e36)
svg from https://svgl.app/

**Comment by miguelsolorio** [comment]
![CleanShot 2024-03-18 at 09 22 20@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/93820a42-2720-4f9e-9086-ac543f3911a1)
