### ISSUE TITLE
Open VSX Support

### ISSUE THREAD

**Issue by NobbyDeveloper** [miguelsolorio/vscode-symbols#170]
Hi! It will be great, add support to [Open VSX](https://open-vsx.org/) to allow Gitpod VSCode Web - VSCodium users use Symbols.

**Comment by miguelsolorio** [comment]
Thanks for the suggestion but I'm not fond of unofficial third-party sites, please see https://github.com/miguelsolorio/vscode-symbols/issues/91#issuecomment-1553880468
