### ISSUE TITLE
Add pkl

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#182]
https://github.com/apple/pkl
https://pkl-lang.org/
https://pkl-lang.org/_/img/favicon.svg

**Comment by miguelsolorio** [comment]
![CleanShot 2024-03-18 at 09 38 56@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/58b10d34-51cc-4a8a-a4e6-96b58f452d01)
