### ISSUE TITLE
.spec.mjs and .test.mjs icons

### ISSUE THREAD

**Issue by calvo-jp** [miguelsolorio/vscode-symbols#184]
`.spec.mjs`, `.test.mjs`, `.test.js` and `.spec.js` should have the same icon (orange)

<img width="146" alt="image" src="https://github.com/miguelsolorio/vscode-symbols/assets/86353187/d7fba523-92a0-496c-851d-d926fe66c165">

**Comment by miguelsolorio** [comment]
![CleanShot 2024-03-27 at 11 44 46@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/388f2984-fa95-42f5-b51b-df54692cc40f)
