### ISSUE TITLE
Add folder for types Interfaces, Models, Router, Helps from Typecsript

### ISSUE THREAD

**Issue by keidsondesigner** [miguelsolorio/vscode-symbols#192]
![Screenshot 2024-03-19 141628](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/c6cf8218-0afa-4057-b8da-664e8b5e76f1)

@miguelsolorio

https://www.figma.com/file/UQQzTjcRvWsZW9udePXOSr/Symbols---File-Icons-(Copy)?type=design&mode=design&t=zIiTKZHz8wKOQz7H-0

**Comment by keidsondesigner** [comment]
![Screenshot 2024-03-19 145744](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/ef9af893-ab80-4ca8-9afe-7c322628c872)

**Comment by miguelsolorio** [comment]
Can you please share what folder names these will map to?

**Comment by keidsondesigner** [comment]
@miguelsolorio  I have named each frame with its proper name

**Comment by keidsondesigner** [comment]
![Screenshot 2024-03-19 165208](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/ea0e270d-9396-40d0-a853-d3053e22c5a3)

**Comment by miguelsolorio** [comment]
Thanks, are you able to create a PR?

**Comment by keidsondesigner** [comment]
@miguelsolorio  can you guide me on how to do this?

**Comment by miguelsolorio** [comment]
Thanks for the suggestions, I omitted `utils` since we already had that one.

![CleanShot 2024-03-27 at 10 34 04@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/6b68ec1a-f527-4c76-a77b-393958e43732)

**Comment by keidsondesigner** [comment]
@miguelsolorio the interfaces folder is named wrong you wrote interface without the "r"

**Comment by miguelsolorio** [comment]
@keidsondesigner thanks for that catch, fixed the typo.

![CleanShot 2024-04-04 at 08 18 29@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/763fcd4d-794b-4958-a245-4926ddd2f00e)


In the meantime you can use the following configuration until the new version is released:

```json
  "symbols.folders.associations": {
    "interfaces": "folder-intefaces",
  }
