### ISSUE TITLE
Add folder for Pipes, Services, Interceptors, Providers from Angular

### ISSUE THREAD

**Issue by keidsondesigner** [miguelsolorio/vscode-symbols#193]
![Screenshot 2024-04-04 072012](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/e2a97ce1-9318-4cff-a9df-86b888f3fc7a)

![Screenshot 2024-04-04 072209](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/539ab173-4231-4c32-9575-429999ad0527)

@miguelsolorio 
link figma:
https://www.figma.com/file/UQQzTjcRvWsZW9udePXOSr/Symbols---File-Icons-(Copy)?type=design&node-id=20521-84115&mode=design&t=BrcviExQerArlIQF-0

**Comment by miguelsolorio** [comment]
Thanks for the suggestions, made some minor edits:

![CleanShot 2024-08-04 at 22 14 08@2x](https://github.com/user-attachments/assets/9c8f8712-b923-46e9-b7ed-b698ab2d7d5a)
