### ISSUE TITLE
different icon for .svelte.ts and .svelte.js files

### ISSUE THREAD

**Issue by calvo-jp** [miguelsolorio/vscode-symbols#204]

**Comment by castrogarciajs** [comment]
Can you explain what you mean by different icons?

**Comment by miguelsolorio** [comment]
I think they mean by different colors like js/ts files:

![CleanShot 2024-06-11 at 20 37 06@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/de7ec48f-442e-4436-bc6f-40fcb5e5cd75)

**Comment by miguelsolorio** [comment]
![CleanShot 2024-06-11 at 22 01 48@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/3c460e61-fd01-4b0f-a49a-d99d093c9538)
