### ISSUE TITLE
nestjs file icons

### ISSUE THREAD

**Issue by williandeitosi** [miguelsolorio/vscode-symbols#207]
please put the other nestjs file icons:

![Captura de tela 2024-05-28 224738](https://github.com/miguelsolorio/vscode-symbols/assets/104787632/ba75b130-a0e0-43a5-9a11-9cd41f617ea7)

**Comment by miguelsolorio** [comment]
Since other file types can override the same file, you'll need to set this in your [user settings](https://github.com/miguelsolorio/vscode-symbols?tab=readme-ov-file#configuration):

```
"symbols.files.associations": {
    "app.controller.ts": "nest",
    "app.module.ts": "nest-module",
    "app.service.ts": "nest-service",
}
```

**Comment by angelhdzmultimedia** [comment]
![image](https://github.com/user-attachments/assets/046e24c0-a2a0-400a-a67c-8997edc8c808)
