### ISSUE TITLE
The "go" and "go mod" icons are very small compared to the others

### ISSUE THREAD

**Issue by brnLucas** [miguelsolorio/vscode-symbols#208]
![image](https://github.com/miguelsolorio/vscode-symbols/assets/104805017/21982f60-56b9-4f54-9096-2cded581910c)

**Comment by miguelsolorio** [comment]
Tried making them as big as I can, their logo has some extra elements on the side that limit its size unlike other logos:

![CleanShot 2024-06-11 at 20 46 36@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/41ea1aad-6f31-4ace-b3e5-8586feb01f68)
