### ISSUE TITLE
Add .config file association

### ISSUE THREAD

**Issue by moraisbrian** [miguelsolorio/vscode-symbols#225]
Is it possible to make the default theme association for files with the .config extension?

Example:
![Screenshot_1](https://github.com/user-attachments/assets/f8bee4e3-7206-4cd7-8a28-b58b6e17ac7a)

At the moment:
![image](https://github.com/user-attachments/assets/fabfca2b-c708-4097-b910-e18a76c3f801)

**Comment by miguelsolorio** [comment]
Yes, I can update the config. For now you can set the following in your user settings ([ref](https://github.com/miguelsolorio/vscode-symbols?tab=readme-ov-file#files)):
```json
  "symbols.files.associations": {
    "file.config": "gear"
  },
```
