### ISSUE TITLE
Extension keeps creating the symbols.hidesExplorerArrows key in settings

### ISSUE THREAD

**Issue by Sutaai** [miguelsolorio/vscode-symbols#232]
Hello,

After using extension bisect, it appears that your extension, as of `v0.0.18`, keeps creating the `symbols.hidesExplorerArrows` setting in the user's settings, even after removing the key entirely.
Disabling the extension is the only way to not trigger this problem.

I understand if this is a voluntary action, but I think this is an undesirable behavior to the user and shall not be "automatically messing with user's settings".

Thank you.

**Comment by miguelsolorio** [comment]
I understand the frustration about having your settings modified without doing anything. This was added in https://github.com/miguelsolorio/vscode-symbols/pull/8 and I'll see if I can spend some time to not write to user settings unless there are changes.

**Comment by miguelsolorio** [comment]
I was able to add some logic to prevent from this issue happening, keep an eye out for v0.0.19 with the fix. Thanks for flagging this ❤️!
