### ISSUE TITLE
[feature] Custom Icons

### ISSUE THREAD

**Issue by angelhdzmultimedia** [miguelsolorio/vscode-symbols#234]
Nice to have an entry in the user/workspace settings to add custom icons.
I add my custom icons in `extensions\miguelsolorio.symbols-0.0.18\src\icons\*` and in `extensions\miguelsolorio.symbols-0.0.18\src\symbol-icon-theme.json` but of course on every extension update it's lost. 😁

**Comment by miguelsolorio** [comment]
I don't understand what your request is. This is a file icon theme, if you want custom icons then I think you need to create your own theme extension.
