### ISSUE TITLE
When is the release of 0.19.0?

### ISSUE THREAD

**Issue by sebastiandotdev** [miguelsolorio/vscode-symbols#235]
Hello @miguelsolorio, I wanted to ask, when do you plan to release the new version of vscode-symbols, you need help with something (remaining)?

Thank you, for reading.

**Comment by miguelsolorio** [comment]
I need more time 😅  hoping to get to it soon (this week) once I review the remaining PRs https://github.com/miguelsolorio/vscode-symbols/pulls

**Comment by miguelsolorio** [comment]
Just published v0.0.19 https://github.com/miguelsolorio/vscode-symbols/releases/tag/0.0.19
