### ISSUE TITLE
Folder Arrows issue on 0.0.19

### ISSUE THREAD

**Issue by zacksmash** [miguelsolorio/vscode-symbols#239]
First off -- love this icon set! Great job!

I'm seeing a weird issue on the latest version where the folder arrows will randomly come back, even if I have the config setting to disable them. It's especially consistent when using spaces on macOS (video added). Happy to add more detail if necessary!

Thanks again, cheers.

<img width="517" alt="Screenshot 2024-09-05 at 3 25 45 PM" src="https://github.com/user-attachments/assets/91597136-3024-4849-add5-6205602d6eb3">

https://github.com/user-attachments/assets/595b4294-9cb3-41a2-ad05-512e1f34a338

**Comment by miguelsolorio** [comment]
Thanks for filing an issue! We did recently make some changes in the logic for this setting in https://github.com/miguelsolorio/vscode-symbols/issues/232. I can't seem to reproduce, would you mind doing the following:

1. remove the `symbols.hidesExplorerArrows` setting
2. reload VS Code
3. re-add the setting and see if it persists

**Comment by zacksmash** [comment]
@miguelsolorio I've followed those instructions and unfortunately it still seems to toggle the arrows visibility when swiping between spaces, or just switching windows. Anything else I can help with?

**Comment by miguelsolorio** [comment]
You can try downgrading the extension and then updating again? And to verify, this only happens when switching spaces? Doesn't happen when you are in a single space?

**Comment by miguelsolorio** [comment]
Ah ok this is super helpful! Let me see if I can bisect the issue. Thanks again!

**Comment by zacksmash** [comment]
You got it! Lmk if there's anything else I can do to help debug. Thanks again for this!

**Comment by miguelsolorio** [comment]
@zacksmash ok I was able to reproduce the bug now and found the line that was causing out, can you install this version and verify that this works for you as well? Want to test it before publishing

[symbols-0.0.20.vsix.zip](https://github.com/user-attachments/files/16901007/symbols-0.0.20.vsix.zip)

**Comment by zacksmash** [comment]
@miguelsolorio That looks like it fixed it! Thanks for the quick response!

I also submitted a PR for a file icon #240, lmk if that looks okay.

https://github.com/user-attachments/assets/25259cb0-868b-49e7-89f0-989f2154c696

**Comment by miguelsolorio** [comment]
Thanks so much for testing, I'll release this out shortly and then will review your PR.

**Comment by miguelsolorio** [comment]
I actually discovered some more issues, whenever you make any edits/changes to your settings the arrows come back. I'll see if I can fix this properly.

https://github.com/user-attachments/assets/e1949e5e-1cfa-42ef-b408-7d634be91363
