### ISSUE TITLE
Support Elixir

### ISSUE THREAD

**Issue by luhagel** [miguelsolorio/vscode-symbols#29]
Heya,
I'm really enjoying the icons and would love to see elixir files supported, especially after seeing how quickly you are hammering out all these other new files.

- Elixir Files (`.ex`) and Elixir Script Files (`.exs`)
- EEx/HEEx Files (`.html.eex`/`.html.leex`/`.html.heex`)

Thank you so much for the great work!

**Comment by miguelsolorio** [comment]
<img width="216" alt="CleanShot 2022-09-26 at 10 52 17@2x" src="https://user-images.githubusercontent.com/35271042/192346320-a28bdae1-301b-43f6-bad5-3aceedfcafe6.png">
