### ISSUE TITLE
Support for `.php` files

### ISSUE THREAD

**Issue by seahindeniz** [miguelsolorio/vscode-symbols#30]
Hi, `php` icon support could be nice.

_I don't like it, but 🥹_

**Comment by miguelsolorio** [comment]
Let's see if this one is fancy enough 😄 

<img width="146" alt="CleanShot 2023-01-13 at 21 15 39@2x" src="https://user-images.githubusercontent.com/35271042/212446233-29535534-a1fc-47b6-a079-b68e2f802863.png">
