### ISSUE TITLE
Add support for `fonts` files

### ISSUE THREAD

**Issue by ameer-taghavi** [miguelsolorio/vscode-symbols#32]
please add support for `.ttf`, `.eot`, `.woff` and ... 🙏🏻

**Comment by miguelsolorio** [comment]
<img width="161" alt="CleanShot 2022-09-26 at 11 07 49@2x" src="https://user-images.githubusercontent.com/35271042/192349037-eaee3a35-b73c-463a-a47a-8bb1578bfad3.png">
