### ISSUE TITLE
Add support for `audio/video` files

### ISSUE THREAD

**Issue by ameer-taghavi** [miguelsolorio/vscode-symbols#33]
please add support for `mp3`, `wav`, `mp4`, `avi`, and other audio/video files 🙏🏻

**Comment by miguelsolorio** [comment]
<img width="205" alt="CleanShot 2023-01-13 at 21 48 58@2x" src="https://user-images.githubusercontent.com/35271042/212447472-a61b84a6-fb8a-4f27-86c6-040376e4561d.png">


<img width="219" alt="CleanShot 2023-01-13 at 21 48 44@2x" src="https://user-images.githubusercontent.com/35271042/212447463-240be76a-c586-401e-9e45-3f8b74c15625.png">
