### ISSUE TITLE
Add support for `.patch` files

### ISSUE THREAD

**Issue by ameer-taghavi** [miguelsolorio/vscode-symbols#34]
as titled 🙏🏻

**Comment by misolori** [comment]
is this a git-related file? i'm not too familiar with them

**Comment by ameer-taghavi** [comment]
> is this a git-related file? i'm not too familiar with them

https://www.npmjs.com/package/patch-package

**Comment by FradSer** [comment]
https://github.com/ds300/patch-package doesn't have offical logo or icon, is the icon below (in #36) suit?
![image](https://user-images.githubusercontent.com/1439628/185416788-f1239301-84a9-4292-962c-b6b3aa8c3a3a.png)

**Comment by miguelsolorio** [comment]
<img width="150" alt="CleanShot 2023-01-13 at 21 53 06@2x" src="https://user-images.githubusercontent.com/35271042/212447597-5b07553b-048c-4b23-aaf9-cc2ced79e7a6.png">
