### ISSUE TITLE
add support/ custom icon for test files (foo.test.js/ foo.test.ts)

### ISSUE THREAD

**Issue by alexn-s** [miguelsolorio/vscode-symbols#35]
love your icons. they look really nice modern.

would you consider adding custom icons for js/ ts test files?

**Comment by misolori** [comment]
I think that is doable, usually they are just a different color so happy to do that.

**Comment by ysjn** [comment]
Would be fantastic if you could support these files with same color as `*.test.*`! :rocket:
`*.spec.js`
`*.spec.jsx`
`*.spec.ts`
`*.spec.tsx`

**Comment by miguelsolorio** [comment]
<img width="223" alt="CleanShot 2023-01-11 at 22 33 25@2x" src="https://user-images.githubusercontent.com/35271042/211969620-edac900d-b8f3-46fb-9f29-3ee6aba2b3b2.png">
