### ISSUE TITLE
`vite.config.ts` icon not working.

### ISSUE THREAD

**Issue by iyashpal** [miguelsolorio/vscode-symbols#39]
![image](https://user-images.githubusercontent.com/19922707/185777233-d068f0ab-5fa9-405a-b135-a9502f506f03.png)

**Comment by rafaelpimpa** [comment]
It's not yet released.

**Comment by miguelsolorio** [comment]
![image](https://user-images.githubusercontent.com/35271042/206826239-ace54d45-429c-4b7c-a3d0-d8003edf36e3.png)
