### ISSUE TITLE
Can't use the icon set on a remote server session

### ISSUE THREAD

**Issue by mmontagnana** [miguelsolorio/vscode-symbols#40]
Hi.

I connect VS Code to a Linux server using the Remote-SSH extension. On the remote servers the Symbols plugin is disabled:

![image](https://user-images.githubusercontent.com/5336731/186884865-95cd9f91-993c-48dd-8e0e-d7cd63165c23.png)

On the remote servers VS Code is using the Seti icon set, in local it uses the Symbols set correctly. I installed the Material Icons Theme as well, and it doesn't need to be installed on the remote server, just like the default Seti and Minimal sets.

I'm using a Mac with M1 processor and macOS 12.5.1 and VS Code 1.70.2.

Thanks, regards.

**Comment by misolori** [comment]
Hmm...I'm not sure why that doesn't work. Let me investigate...

**Comment by misolori** [comment]
@mmontagnana what happens when you click "install in SSH"? I tried this in a Codespace, which is also a remote env, and got a similar message but clicking install will install it.

**Comment by mmontagnana** [comment]
If I install it in remote it works.

The issue is that, for example, the Material File Icon theme and the Fluent product icon theme are working from the local install, with no need to install them in SSH.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/5336731/187376622-8b2f66ed-3e27-4455-828b-131eb76c36eb.png">

**Comment by misolori** [comment]
Yes, that's because each extension is created differently. The symbol icon extension runs javascript to dynamically create the non-chevron tree items, so that's why it needs to be installed.

**Comment by mmontagnana** [comment]
Ok, if it's by design I'll install it on the other VMs I'm using.

Thank you, regards
Marco

**Comment by miguelsolorio** [comment]
Closing in favor of https://github.com/miguelsolorio/vscode-symbols/issues/46
