### ISSUE TITLE
Custom icon for `.editorconfig`

### ISSUE THREAD

**Issue by calvo-jp** [miguelsolorio/vscode-symbols#41]
Hi! I hope we could get a custom icon for `.editorconfig`.  Really like this theme. Thanks a lot, man. 🚀

**Comment by FradSer** [comment]
@calvo-jp any more information about `.editorconfig`?

**Comment by calvo-jp** [comment]
Hi, @FradSer. Currently `.editorconfig`'s icon is cog same with `.env` files. Would be really cool to have `.editorconfig`'s [logo](https://editorconfig.org/logo.png) for anyone to easily spot it. Thanks

**Comment by francmarin98** [comment]
![image](https://user-images.githubusercontent.com/50973629/198902428-d8fdeee7-854e-4e03-9fd1-cceb1b524fd1.png)
What think about?

**Comment by calvo-jp** [comment]
@francmarin98 looks good. thanks man

**Comment by miguelsolorio** [comment]
I've been trying to be a little creative and use alternate icons instead of logos if I can help it to make it fit in with the design of the file icons. So I'd appreciate any ideas/suggestions that fit within the current design aesthetic.

**Comment by miguelsolorio** [comment]
Fixed via https://github.com/miguelsolorio/vscode-symbols/commit/3e8bbe07bf636951dd953ff3df87b60e2de9535b

<img width="161" alt="CleanShot 2023-05-01 at 10 18 43@2x" src="https://user-images.githubusercontent.com/35271042/235495534-fcee16d1-b870-4c20-9e89-e66529f91e20.png">


<img width="216" alt="CleanShot 2023-05-01 at 10 18 31@2x" src="https://user-images.githubusercontent.com/35271042/235495511-6f735aea-903c-4b5b-a538-dbf0b8b8e194.png">
