### ISSUE TITLE
HTTP language support

### ISSUE THREAD

**Issue by jezikk** [miguelsolorio/vscode-symbols#43]
It would be nice to have icons for HTTP language used for example by [Restclient](https://github.com/Huachao/vscode-restclient).
- .http
- .rest

**Comment by miguelsolorio** [comment]
<img width="164" alt="CleanShot 2023-01-13 at 21 23 56@2x" src="https://user-images.githubusercontent.com/35271042/212446530-c19be773-05d2-42aa-8177-b9c6a5d6d665.png">
