### ISSUE TITLE
terraform icon

### ISSUE THREAD

**Issue by WgkLink** [miguelsolorio/vscode-symbols#52]
Add a terraform icon

**Comment by WgkLink** [comment]
https://www.svgrepo.com/svg/376353/terraform

**Comment by miguelsolorio** [comment]
Fixed via https://github.com/miguelsolorio/vscode-symbols/pull/54

<img width="277" alt="CleanShot 2022-12-09 at 18 29 32@2x" src="https://user-images.githubusercontent.com/35271042/206824381-f6a7826e-4f46-430b-a281-629af34aff88.png">
