### ISSUE TITLE
.exe file icon

### ISSUE THREAD

**Issue by aoyewol2** [miguelsolorio/vscode-symbols#53]
When working with C, I need to compile C programs to a .exe file to run them. An icon for .exe files would be very helpful in differentiating different files.
![image](https://user-images.githubusercontent.com/34896708/194740224-05d15474-92e7-4c64-bfb2-59f2033150d1.png)

**Comment by miguelsolorio** [comment]
<img width="203" alt="CleanShot 2023-01-13 at 18 09 11@2x" src="https://user-images.githubusercontent.com/35271042/212435274-eb7a9d9a-85f4-43a2-890b-0cba71a24a36.png">
