### ISSUE TITLE
add support to .jenkinsfile files

### ISSUE THREAD

**Issue by dgosza** [miguelsolorio/vscode-symbols#59]

**Comment by dgosza** [comment]
icon request pls

**Comment by miguelsolorio** [comment]
v0.0.8 has support for jenkins files (via https://github.com/miguelsolorio/vscode-symbols/pull/54)

<img width="221" alt="CleanShot 2023-01-12 at 09 08 02@2x" src="https://user-images.githubusercontent.com/35271042/212088100-79612d5e-68b2-4938-baba-5b05b7897df6.png">
