### ISSUE TITLE
What's the theme name from the screenshot?

### ISSUE THREAD

**Issue by cmarincia** [miguelsolorio/vscode-symbols#61]
![image](https://user-images.githubusercontent.com/35623921/207324045-05b6d4de-cb33-4f23-931f-1134fe0768cd.png)

**Comment by javimarsal** [comment]
You can look for "Symbols" on the extensions menu in vs code. After installing it, you can go to `File > Preferences > File Icon Theme` and then select "Symbol Icons".

**Comment by cmarincia** [comment]
I meant the UI theme

**Comment by javimarsal** [comment]
Ah yes, that is called "Fluent Icons". You can find it on the extensions menu too.
![imagen](https://user-images.githubusercontent.com/32175277/209224118-b61e35ef-254d-445b-a972-35276603fbcb.png)

**Comment by miguelsolorio** [comment]
Product Icon Theme is [Fluent Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons), Color Theme is [Moonlight](https://marketplace.visualstudio.com/items?itemName=atomiks.moonlight).
