### ISSUE TITLE
Icons for other hosting providers like firebase

### ISSUE THREAD

**Issue by jacobthesheep** [miguelsolorio/vscode-symbols#70]
- .vercel
- vercel.json
- netlify.toml
- deno.json
and others

**Comment by miguelsolorio** [comment]
> and others

Please do list what the others are 😃

**Comment by jacobthesheep** [comment]
Those are the popular ones I know

**Comment by miguelsolorio** [comment]
![image](https://user-images.githubusercontent.com/35271042/235495333-1117cdb0-2344-4461-8344-9ee2698b68dd.png)
