### ISSUE TITLE
Icon for "client" folder

### ISSUE THREAD

**Issue by jezikk** [miguelsolorio/vscode-symbols#71]
If there is the icon for "server" folder it would be nice to have a icon for "client" folder too.

**Comment by miguelsolorio** [comment]
<img width="198" alt="CleanShot 2023-05-01 at 10 42 48@2x" src="https://user-images.githubusercontent.com/35271042/235499290-d70b5267-42b3-4e9f-81a3-e4f941ab8673.png">
