### ISSUE TITLE
Add the possibility to set folders/files associations

### ISSUE THREAD

**Issue by devzgabriel** [miguelsolorio/vscode-symbols#73]
In material-icon-theme extension, we can associate files with other's appearance:

```json
"material-icon-theme.folders.associations": {
    "infra": "app",
    "entities": "class",
    "schemas": "class",
}
```

The main problem is a Nest.js project with Angularjs icons.

It would be interesting to see the same behavior in Symbols extension

**Comment by wmartinezh** [comment]
This feature will be a game-changing

**Comment by NandoMB** [comment]
https://github.com/miguelsolorio/vscode-symbols/pull/92

**Comment by miguelsolorio** [comment]
You can now set custom file and folder associations thanks to @wladimirgrf in #92. You can use `symbols.folders.associations` and `symbols.files.associations` like so (in your settings.json):

```json
  "symbols.folders.associations": {
    "infra": "folder-app",
    "entities": "folder-assets",
    "schemas": "folder-purple"
  },
```
and for files:
```json
  "symbols.files.associations": {
    "app.module.ts": "ts",
    "service.module.ts": "ts"
  },
```

You can find the full list of folder & file icon names [in the source files](https://github.com/miguelsolorio/vscode-symbols/blob/ab14a3f9def1af43a86f3965df72d0d9960524a6/src/symbol-icon-theme.json#L3-L33).
