### ISSUE TITLE
Icons For ColdFusion Markup Language

### ISSUE THREAD

**Issue by rahulduttt** [miguelsolorio/vscode-symbols#74]
Really love this Icon theme, requesting if we could please get icons for ColdFusion:
- *.cfc
- *.cfm

Thank you

**Comment by miguelsolorio** [comment]
<img width="155" alt="CleanShot 2023-05-05 at 09 08 20@2x" src="https://user-images.githubusercontent.com/35271042/236510489-c56f6b56-032b-427b-8496-6c677330c949.png">
