### ISSUE TITLE
Swift icon is too big compared to other icons

### ISSUE THREAD

**Issue by svipas** [miguelsolorio/vscode-symbols#76]
### Swift icon
<img width="222" alt="SCR-20230122-w7i" src="https://user-images.githubusercontent.com/10441177/213940624-91a9b32a-1f44-45df-84eb-4ee2fb6ed5f7.png">

### Other icons
<img width="146" alt="SCR-20230122-w7m" src="https://user-images.githubusercontent.com/10441177/213940633-f5d29ab2-367f-4030-aec6-a2aec49da4a3.png">
<img width="107" alt="SCR-20230122-w7u" src="https://user-images.githubusercontent.com/10441177/213940645-837b072c-c2aa-4c30-b991-635bce05c85e.png">

**Comment by miguelsolorio** [comment]
<img width="218" alt="CleanShot 2023-05-05 at 09 14 25@2x" src="https://user-images.githubusercontent.com/35271042/236511851-94ac08d1-1aa8-4f9b-b18b-fff02be3c25e.png">
