### ISSUE TITLE
Icon for shopify *.liquid files.

### ISSUE THREAD

**Issue by JasieBasie** [miguelsolorio/vscode-symbols#78]
Suggestions:
- shopify logo
- water drop

**Comment by miguelsolorio** [comment]
@JasieBasie I'm seeing 0.0.10 as the latest version on the marketplace:

<img width="704" alt="CleanShot 2023-05-12 at 09 49 28@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/fc0cc18d-b175-47e1-b394-c18d05be6bcb">

<img width="357" alt="CleanShot 2023-05-12 at 09 50 08@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/b72c9e1d-86cf-4aa2-9f63-bdc69afb7059">


You might check to see if there are extension updates in the Extension view
