### ISSUE TITLE
Add ability to select 'nest.js' or 'angular.js'

### ISSUE THREAD

**Issue by obnol** [miguelsolorio/vscode-symbols#82]
Since Nest.js and Angular.js' file naming are the same (*.module.ts, *.service.ts); could it be possible to switch between those two frameworks? Right now, *.module.ts defaults to Angular icon.

**Comment by wmartinezh** [comment]
I'm constantly working with Nest.JS and I would like nest.js icons can be integrated sooner because currently, I'm using `Helium icons` but I love Symbols I hope this feature can be supported.

**Comment by miguelsolorio** [comment]
You can now assign specific icons for certain file paths like:

```json
  "symbols.files.associations": {
    "app.module.ts": "ts",
    "service.module.ts": "ts"
  },
```
You can find the full list of folder & file icon names [in the source files](https://github.com/miguelsolorio/vscode-symbols/blob/ab14a3f9def1af43a86f3965df72d0d9960524a6/src/symbol-icon-theme.json) or view [a preview of them](https://www.figma.com/file/HYLMyRbIdSbIJQlqnd9pSN/Symbols---File-Icons?node-id=20521%3A84115&t=PyBzZOlVG5TXyEdx-1) in Figma.

For `*` wildcard support, we'll need to support from the VS Code extension API, which is covered in #93.

**Comment by miguelsolorio** [comment]
You can use `*` in files association using the following setting configuration via https://github.com/miguelsolorio/vscode-symbols/issues/93:

```json
"symbols.files.associations": {
    "*.service.ts": "nest",
    "*.module.ts": "nest"
},
```
