### ISSUE TITLE
Add .csproj and .sln file icon

### ISSUE THREAD

**Issue by evertonandrade** [miguelsolorio/vscode-symbols#85]
![image](https://user-images.githubusercontent.com/43795982/235796213-20303309-9b25-4427-b506-d8384119b8b5.png)

**Comment by miguelsolorio** [comment]
<img width="224" alt="CleanShot 2023-05-05 at 14 53 19@2x" src="https://user-images.githubusercontent.com/35271042/236574869-29b9744b-456a-415b-ae78-a7dc6789cee6.png">
