### ISSUE TITLE
Request for Clearer Expanded/Collapsed Folder Indication

### ISSUE THREAD

**Issue by kud** [miguelsolorio/vscode-symbols#88]
Hi,

Thanks for the great theme! I have a suggestion to improve it: could you make it easier to differentiate between expanded and collapsed folders in the file explorer? Maybe using color variations, shading, or visual indicators like arrows or plus/minus signs.

Looking forward to any enhancements. Appreciate your work!

Best,

**Comment by miguelsolorio** [comment]
Combining this wiht #49 since it is requesting the same thing

**Comment by kud** [comment]
Thanks 😌
