### ISSUE TITLE
Add .njk file icon

### ISSUE THREAD

**Issue by jacobthesheep** [miguelsolorio/vscode-symbols#89]
[Nunjunks](https://mozilla.github.io/nunjucks/) file extension
[Icon](https://mozilla.github.io/nunjucks/img/favicon.png)

**Comment by miguelsolorio** [comment]
<img width="191" alt="CleanShot 2023-05-30 at 15 10 13@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/ec606314-07f3-40ec-9e39-f20d02aac716">
