### ISSUE TITLE
Add support to qwik icons

### ISSUE THREAD

**Issue by falvarador** [miguelsolorio/vscode-symbols#90]
Hi, can you add Qwik icon support to js, jsx, ts and tsx files extensions? 

[Qwik main page](https://qwik.builder.io/)
[Qwik icon](https://qwik.builder.io/favicons/favicon.svg)

Thanks for you work Miguel!

**Comment by miguelsolorio** [comment]
@falvarador Thanks for the request, I'm not too familiar with this and wasn't able to find specific file types for these. Can you link to any examples and include what file extensions they use? You mention js/jsx/ts but those have their own file icons. Thanks!

**Comment by miguelsolorio** [comment]
If you ever get a list of file types let me know, otherwise I'll be closing this issue.
