### ISSUE TITLE
Allow wildcards in files association

### ISSUE THREAD

**Issue by miguelsolorio** [miguelsolorio/vscode-symbols#93]
It would be great to add `*` support for files association like:

```json
  "symbols.files.associations": {
    "*.module.ts": "ts",
  }
```
as right now you have to match the exact name for it to work (`app.module.ts`), which can get tedious.

FYI @wladimirgrf

**Comment by wladimirgrf** [comment]
Nice, it's a good feature, I can take a look at how to implement it.

**Comment by miguelsolorio** [comment]
Started looking into this and this is not supported by the VS Code extension API https://github.com/Microsoft/vscode/issues/12493

**Comment by wladimirgrf** [comment]
Maybe there is a way to do it, **material-icon-theme** has that feature.

About the https://github.com/miguelsolorio/vscode-symbols/pull/92, did you test it? It work fine for you?

**Comment by miguelsolorio** [comment]
They have the same issue https://github.com/PKief/vscode-material-icon-theme/issues/330 and yes the current file association works, you have to match the name exactly.

**Comment by wladimirgrf** [comment]
Yes, we can make the simplest version, it already solves most cases.
I asked about the last PR, because I'm testing the official extension and I need to reload the window every time I change the `settings.json` (_to update the icons_).

**Comment by miguelsolorio** [comment]
Ah, I thought that was the expected behavior? At least when I tested it with the material icons it also worked the same way (icon only changes after reload)

**Comment by wladimirgrf** [comment]
hmm I see, I wasn't 100% sure how it would look after publishing. 
This is the first extension project for VsCode that I work on.

The idea was to behave exactly like material-icons, as soon as the `settings.json` is updated so is the icon.

I will try to do this. If everything goes well I'll open another PR.

**Comment by zm-cttae** [comment]
`*.module.ts` is just a non-standard `fileExtensions` key to be fair!

**Comment by miguelsolorio** [comment]
Fixed via https://github.com/miguelsolorio/vscode-symbols/pull/101
