### ISSUE TITLE
Yellow folder not working when custom theme

### ISSUE THREAD

**Issue by devgustavovasquez** [miguelsolorio/vscode-symbols#94]
![image](https://github.com/miguelsolorio/vscode-symbols/assets/78443398/cb7bf7fe-b918-4080-b49f-e2ce85849d67)

**Comment by miguelsolorio** [comment]
Good catch, it looks like the yellow folder never made it into the repository. I'll add it shortly.

**Comment by miguelsolorio** [comment]
This will make it into the next release:

<img width="210" alt="CleanShot 2023-05-31 at 14 31 22@2x" src="https://github.com/miguelsolorio/vscode-symbols/assets/35271042/d9fe2960-517b-4b08-bfed-0029d6b8273d">
